package com.ruhul.pojo;
// Generated Feb 24, 2018 11:43:50 PM by Hibernate Tools 4.3.1

import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;




/**
 * Userlogin generated by hbm2java
 */
public class Userlogin  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;

    public Userlogin() {
    }

    public Userlogin(String username, String password, String email) {
       this.username = username;
       this.password = password;
       this.email = email;
    }
   
    @Id
    @GeneratedValue(strategy = IDENTITY)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


